### ISSUE TITLE
reset command is not working

### ISSUE THREAD

**Issue by Ritesh236** [AcSiP/linkit-smart-7688-uboot#3]
Hi all,

I have compiled and updated u-boot in AI7688 module.
u-boot version: U-Boot 1.1.3
Before updation reset command was working.

I have taken fresh U-boot code from the git link mentioned below
Git Link: https://github.com/AcSiP/linkit-smart-7688-uboot.git

But, now reset command is not working. When i gone through the code in depth then I got the below mentioned code.

#define SOFTRES_REG (RALINK_SYSCTL_BASE + 0x0034)
#define GORESET		(0x01)

int do_reset(cmd_tbl_t *cmdtp, int flag, int argc, char *argv[])
{
	*(volatile unsigned int*)(SOFTRES_REG) = GORESET;
	return 1;
}
#endif
I have checked the register address its also correct for both control and status register for Reset Functionality.

But, then also reset command is not working.

Can someone please let me know how can I make the command work? Or let me know if anyone has any clue to fix it. 

Let me know if need anything else from my end or need more information for the same. 

Regards, 
Ritesh Prajapati

**Comment by Yunlin0110** [comment]
Hi Ritesh,

What is your flash capacity? If your flash capacity is 64MB, you should switch branch to AI7688H__64MB.
link: [https://github.com/AcSiP/linkit-smart-7688-uboot/tree/AI7688H__64MB](url)

u-boot version : U-Boot 1.1.3 for AI7688H-64MB

Best wishes,
Yunlin

**Comment by Ritesh236** [comment]
> Hi Ritesh,
> 
> What is your flash capacity? If your flash capacity is 64MB, you should switch branch to AI7688H__64MB. link: [https://github.com/AcSiP/linkit-smart-7688-uboot/tree/AI7688H__64MB](url)
> 
> u-boot version : U-Boot 1.1.3 for AI7688H-64MB
> 
> Best wishes, Yunlin

Hello @Yunlin0110 ,

Thanks for your prompt response.

We are using 64 MB Flash Memory Module at our end. I have checked like both version are same but still let me check and get back to you ASAP

Regards,
Ritesh Prajapati

**Comment by Ritesh236** [comment]
Hello @Yunlin0110 ,

Sorry as there was my mistake to see branch. I have again checked and it seems to be fixed reset issue. So, We will verify it over here after updating boot loader and let you know updates for the same.

Regards,
Ritesh Prajapati

**Comment by Ritesh236** [comment]
Hello @Yunlin0110 , 

We have checked with other than master branch and it is working fine means reset command is working properly as per requirements and same for r boot command from file system. 

Thank you very much for your great help and appreciate it. 

You can close this issue now. 

Regards, 
Ritesh Prajapati
